package com.splanes.uoc.wishlify.presentation.infrastructure.theme.colors.palette

import androidx.compose.ui.graphics.Color
import com.splanes.uoc.wishlify.presentation.infrastructure.theme.colors.AppColorScheme

private val primaryDark = Color(0xFF88D1EC)
private val onPrimaryDark = Color(0xFF003543)
private val primaryContainerDark = Color(0xFF004E60)
private val onPrimaryContainerDark = Color(0xFFB7EAFF)
private val secondaryDark = Color(0xFFB3CAD4)
private val onSecondaryDark = Color(0xFF1E333B)
private val secondaryContainerDark = Color(0xFF344A52)
private val onSecondaryContainerDark = Color(0xFFCFE6F1)
private val tertiaryDark = Color(0xFFF0BF6D)
private val onTertiaryDark = Color(0xFF422C00)
private val tertiaryContainerDark = Color(0xFF5F4100)
private val onTertiaryContainerDark = Color(0xFFFFDEAB)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val successDark = Color(0xFFA4D396)
private val onSuccessDark = Color(0xFF10380C)
private val successContainerDark = Color(0xFF275021)
private val onSuccessContainerDark = Color(0xFFBFEFB0)
private val warningDark = Color(0xFFEBC16C)
private val onWarningDark = Color(0xFF402D00)
private val warningContainerDark = Color(0xFF5C4200)
private val onWarningContainerDark = Color(0xFFFFDEA2)
private val infoDark = Color(0xFFA5C8FF)
private val onInfoDark = Color(0xFF00315E)
private val infoContainerDark = Color(0xFF214876)
private val onInfoContainerDark = Color(0xFFD4E3FF)
private val backgroundDark = Color(0xFF0F1416)
private val onBackgroundDark = Color(0xFFDEE3E6)
private val surfaceDark = Color(0xFF0F1416)
private val onSurfaceDark = Color(0xFFDEE3E6)
private val surfaceVariantDark = Color(0xFF40484C)
private val onSurfaceVariantDark = Color(0xFFBFC8CC)
private val outlineDark = Color(0xFF8A9296)
private val outlineVariantDark = Color(0xFF40484C)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFDEE3E6)
private val inverseOnSurfaceDark = Color(0xFF2C3134)
private val inversePrimaryDark = Color(0xFF06677F)
private val surfaceDimDark = Color(0xFF0F1416)
private val surfaceBrightDark = Color(0xFF353A3C)
private val surfaceContainerLowestDark = Color(0xFF0A0F11)
private val surfaceContainerLowDark = Color(0xFF171C1F)
private val surfaceContainerDark = Color(0xFF1B2023)
private val surfaceContainerHighDark = Color(0xFF252B2D)
private val surfaceContainerHighestDark = Color(0xFF303638)
private val surfaceTintDark = Color(0xFF69D4F7)
private val primaryFixedDark = Color(0xFFB7EAFF)
private val primaryFixedDimDark = Color(0xFF69D4F7)
private val onPrimaryFixedDark = Color(0xFF001F28)
private val onPrimaryFixedVariantDark = Color(0xFF004E60)
private val secondaryFixedDark = Color(0xFFC3E8F8)
private val secondaryFixedDimDark = Color(0xFFA7CCDC)
private val onSecondaryFixedDark = Color(0xFF001F28)
private val onSecondaryFixedVariantDark = Color(0xFF274B58)
private val tertiaryFixedDark = Color(0xFFFFDEAB)
private val tertiaryFixedDimDark = Color(0xFFE5C18A)
private val onTertiaryFixedDark = Color(0xFF281900)
private val onTertiaryFixedVariantDark = Color(0xFF5B4317)

internal val DarkColorScheme = AppColorScheme(
  primary = primaryDark,
  onPrimary = onPrimaryDark,
  primaryContainer = primaryContainerDark,
  onPrimaryContainer = onPrimaryContainerDark,
  inversePrimary = inversePrimaryDark,
  secondary = secondaryDark,
  onSecondary = onSecondaryDark,
  secondaryContainer = secondaryContainerDark,
  onSecondaryContainer = onSecondaryContainerDark,
  tertiary = tertiaryDark,
  onTertiary = onTertiaryDark,
  tertiaryContainer = tertiaryContainerDark,
  onTertiaryContainer = onTertiaryContainerDark,
  background = backgroundDark,
  onBackground = onBackgroundDark,
  surface = surfaceDark,
  onSurface = onSurfaceDark,
  surfaceVariant = surfaceVariantDark,
  onSurfaceVariant = onSurfaceVariantDark,
  surfaceTint = surfaceTintDark,
  inverseSurface = inverseSurfaceDark,
  inverseOnSurface = inverseOnSurfaceDark,
  error = errorDark,
  onError = onErrorDark,
  errorContainer = errorContainerDark,
  onErrorContainer = onErrorContainerDark,
  success = successDark,
  onSuccess = onSuccessDark,
  successContainer = successContainerDark,
  onSuccessContainer = onSuccessContainerDark,
  warning = warningDark,
  onWarning = onWarningDark,
  warningContainer = warningContainerDark,
  onWarningContainer = onWarningContainerDark,
  info = infoDark,
  onInfo = onInfoDark,
  infoContainer = infoContainerDark,
  onInfoContainer = onInfoContainerDark,
  outline = outlineDark,
  outlineVariant = outlineVariantDark,
  scrim = scrimDark,
  surfaceBright = surfaceBrightDark,
  surfaceDim = surfaceDimDark,
  surfaceContainer = surfaceContainerDark,
  surfaceContainerHigh = surfaceContainerHighDark,
  surfaceContainerHighest = surfaceContainerHighestDark,
  surfaceContainerLow = surfaceContainerLowDark,
  surfaceContainerLowest = surfaceContainerLowestDark,
  primaryFixed = primaryFixedDark,
  primaryFixedDim = primaryFixedDimDark,
  onPrimaryFixed = onPrimaryFixedDark,
  onPrimaryFixedVariant = onPrimaryFixedVariantDark,
  secondaryFixed = secondaryFixedDark,
  secondaryFixedDim = secondaryFixedDimDark,
  onSecondaryFixed = onSecondaryFixedDark,
  onSecondaryFixedVariant = onSecondaryFixedVariantDark,
  tertiaryFixed = tertiaryFixedDark,
  tertiaryFixedDim = tertiaryFixedDimDark,
  onTertiaryFixed = onTertiaryFixedDark,
  onTertiaryFixedVariant = onTertiaryFixedVariantDark,
)