package com.splanes.uoc.wishlify.presentation.infrastructure.theme.colors.palette

import androidx.compose.ui.graphics.Color
import com.splanes.uoc.wishlify.presentation.infrastructure.theme.colors.AppColorScheme

private val primaryLight = Color(0xFF06677F)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFB7EAFF)
private val onPrimaryContainerLight = Color(0xFF004E60)
private val secondaryLight = Color(0xFF4C626A)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFCFE6F1)
private val onSecondaryContainerLight = Color(0xFF344A52)
private val tertiaryLight = Color(0xFF7C580D)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFFDEAB)
private val onTertiaryContainerLight = Color(0xFF5F4100)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val successLight = Color(0xFF3F6836)
private val onSuccessLight = Color(0xFFFFFFFF)
private val successContainerLight = Color(0xFFBFEFB0)
private val onSuccessContainerLight = Color(0xFF275021)
private val warningLight = Color(0xFF79590C)
private val onWarningLight = Color(0xFFFFFFFF)
private val warningContainerLight = Color(0xFFFFDEA2)
private val onWarningContainerLight = Color(0xFF5C4200)
private val infoLight = Color(0xFF3C6090)
private val onInfoLight = Color(0xFFFFFFFF)
private val infoContainerLight = Color(0xFFD4E3FF)
private val onInfoContainerLight = Color(0xFF214876)
private val backgroundLight = Color(0xFFF5FAFD)
private val onBackgroundLight = Color(0xFF171C1F)
private val surfaceLight = Color(0xFFF5FAFD)
private val onSurfaceLight = Color(0xFF171C1F)
private val surfaceVariantLight = Color(0xFFDBE4E8)
private val onSurfaceVariantLight = Color(0xFF40484C)
private val outlineLight = Color(0xFF70787C)
private val outlineVariantLight = Color(0xFFBFC8CC)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF2C3134)
private val inverseOnSurfaceLight = Color(0xFFEDF1F4)
private val inversePrimaryLight = Color(0xFF88D1EC)
private val surfaceDimLight = Color(0xFFD6DBDE)
private val surfaceBrightLight = Color(0xFFF5FAFD)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFEFF4F7)
private val surfaceContainerLight = Color(0xFFEAEFF1)
private val surfaceContainerHighLight = Color(0xFFE4E9EC)
private val surfaceContainerHighestLight = Color(0xFFDEE3E6)
private val surfaceTintLight = Color(0xFF00677F)
private val primaryFixedLight = Color(0xFFB7EAFF)
private val primaryFixedDimLight = Color(0xFF69D4F7)
private val onPrimaryFixedLight = Color(0xFF001F28)
private val onPrimaryFixedVariantLight = Color(0xFF004E60)
private val secondaryFixedLight = Color(0xFFC3E8F8)
private val secondaryFixedDimLight = Color(0xFFA7CCDC)
private val onSecondaryFixedLight = Color(0xFF001F28)
private val onSecondaryFixedVariantLight = Color(0xFF274B58)
private val tertiaryFixedLight = Color(0xFFFFDEAB)
private val tertiaryFixedDimLight = Color(0xFFE5C18A)
private val onTertiaryFixedLight = Color(0xFF281900)
private val onTertiaryFixedVariantLight = Color(0xFF5B4317)


internal val LightColorScheme = AppColorScheme(
  primary = primaryLight,
  onPrimary = onPrimaryLight,
  primaryContainer = primaryContainerLight,
  onPrimaryContainer = onPrimaryContainerLight,
  inversePrimary = inversePrimaryLight,
  secondary = secondaryLight,
  onSecondary = onSecondaryLight,
  secondaryContainer = secondaryContainerLight,
  onSecondaryContainer = onSecondaryContainerLight,
  tertiary = tertiaryLight,
  onTertiary = onTertiaryLight,
  tertiaryContainer = tertiaryContainerLight,
  onTertiaryContainer = onTertiaryContainerLight,
  background = backgroundLight,
  onBackground = onBackgroundLight,
  surface = surfaceLight,
  onSurface = onSurfaceLight,
  surfaceVariant = surfaceVariantLight,
  onSurfaceVariant = onSurfaceVariantLight,
  surfaceTint = surfaceTintLight,
  inverseSurface = inverseSurfaceLight,
  inverseOnSurface = inverseOnSurfaceLight,
  error = errorLight,
  onError = onErrorLight,
  errorContainer = errorContainerLight,
  onErrorContainer = onErrorContainerLight,
  success = successLight,
  onSuccess = onSuccessLight,
  successContainer = successContainerLight,
  onSuccessContainer = onSuccessContainerLight,
  warning = warningLight,
  onWarning = onWarningLight,
  warningContainer = warningContainerLight,
  onWarningContainer = onWarningContainerLight,
  info = infoLight,
  onInfo = onInfoLight,
  infoContainer = infoContainerLight,
  onInfoContainer = onInfoContainerLight,
  outline = outlineLight,
  outlineVariant = outlineVariantLight,
  scrim = scrimLight,
  surfaceBright = surfaceBrightLight,
  surfaceDim = surfaceDimLight,
  surfaceContainer = surfaceContainerLight,
  surfaceContainerHigh = surfaceContainerHighLight,
  surfaceContainerHighest = surfaceContainerHighestLight,
  surfaceContainerLow = surfaceContainerLowLight,
  surfaceContainerLowest = surfaceContainerLowestLight,
  primaryFixed = primaryFixedLight,
  primaryFixedDim = primaryFixedDimLight,
  onPrimaryFixed = onPrimaryFixedLight,
  onPrimaryFixedVariant = onPrimaryFixedVariantLight,
  secondaryFixed = secondaryFixedLight,
  secondaryFixedDim = secondaryFixedDimLight,
  onSecondaryFixed = onSecondaryFixedLight,
  onSecondaryFixedVariant = onSecondaryFixedVariantLight,
  tertiaryFixed = tertiaryFixedLight,
  tertiaryFixedDim = tertiaryFixedDimLight,
  onTertiaryFixed = onTertiaryFixedLight,
  onTertiaryFixedVariant = onTertiaryFixedVariantLight,
)